[server]
headless = true
address = "localhost"
port = 8501

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[theme]
primaryColor = "#2997ff"
backgroundColor = "#000000"
secondaryBackgroundColor = "#0a0a0a"
textColor = "#f5f5f7"
font = "sans serif"

[client]
showErrorDetails = false
toolbarMode = "minimal"
